name: Test Retry Action
on:
  pull_request:
    paths:
      - '.github/workflows/test-retry.yml'
      - 'retry/action.yaml'
  workflow_dispatch:

jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test retry with eventual success
        uses: ultralytics/actions/retry@test-retry
        with:
          retries: 2
          retry_delay_seconds: 5
          run: |
            echo "Running attempt" 
            false # Force failure to trigger retry

      - name: Test successful command
        uses: ultralytics/actions/retry@test-retry
        with:
          run: |
            echo "This should succeed first try"
            true

      - name: Test multi-line failure
        uses: ultralytics/actions/retry@test-retry
        continue-on-error: true
        with:
          retries: 2
          retry_delay_seconds: 5
          run: |
            echo "Line 1 works"
            echo "Line 2 fails"
            bad_command_here
