name: Test Retry Action
on:
  pull_request:
    paths:
      - '.github/workflows/test-retry.yml'
      - 'retry/action.yaml'
  workflow_dispatch:

jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test successful command
        uses: ultralytics/actions/retry@test-retry
        with:
          run: |
            echo "This should succeed first try"
            true

      - name: Test retry with eventual success
        uses: ultralytics/actions/retry@test-retry
        continue-on-error: true
        env:
          TEST_VAR: "hello"
        with:
          retries: 2
          retry_delay_seconds: 5
          run: |
            echo "Running attempt with TEST_VAR=$TEST_VAR"
            false

      - name: Test multi-line failure
        uses: ultralytics/actions/retry@test-retry
        continue-on-error: true
        env:
          TEST_VAR: "hello"
        with:
          retries: 2
          retry_delay_seconds: 5
          run: |
            echo "Running line 1 with TEST_VAR=$TEST_VAR"
            echo "Running line 2 with TEST_VAR=$TEST_VAR"
            false
